### PR TITLE
PR Test of a Failing Test

### PR DESCRIPTION
**Pull request by william76**

### CODE REVIEW

**Comment by BSSW-Entity** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by BSSW-Entity** [comment]
Status Flag 'Pull Request AutoTest' - Testing Jenkins Projects:

Pull Request Auto Testing STARTING
------------------------------------

## Build Information
- Test Name: BSSW_PR_AutoTest
- Build Num: 22
- Status: STARTED

### Jenkins Parameters
| Parameter Name | Value |
|----------------|-------|
| BSSW_SOURCE_BRANCH | pr-test-fail-02 |
| BSSW_SOURCE_REPO | https://github.com/william76/betterscientificsoftware.github.io |
| BSSW_SOURCE_SHA | a119f6b93d9027a972d60ad6e5ddb898ab3c5a3b |
| BSSW_TARGET_BRANCH | develop |
| BSSW_TARGET_REPO | https://github.com/william76/betterscientificsoftware.github.io |
| BSSW_TARGET_SHA | f2c52140450cd343c6fb8e40c5c6d00e9be283f2 |
| JENKINS_JOB_TYPE | Experimental |
| TEST_REPO_ALIAS | BSSW |

## Using Repos:
- Repo: BSSW (william76/betterscientificsoftware.github.io)
- Branch: pr-test-fail-02
- SHA: a119f6b93d9027a972d60ad6e5ddb898ab3c5a3b
- Mode: TEST_REPO

Pull Request Author: william76 (William)

**Comment by BSSW-Entity** [comment]
Status Flag 'Pull Request AutoTest' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4:00:00. If a change to the Pull Request source branch occurs, the testing will be attempted again.

Pull Request Auto Testing has FAILED
------------------------------------
## Failure Message(s)
```
File: test/test_001_fail.md
Invalid value for property 'Topics', given value 'documentation'.
>>> Failed depenency check against property/value pair 'Categories'/'['Planning', 'Reliability', 'Collaboration', 'Crosscutting', 'Performance']'
>>> Allowable values are:
>>> - 'Continuous integration testing'
>>> - 'Debugging'
>>> - 'Design'
>>> - 'Discussion forums'
>>> - 'Funding sources and programs'
>>> - 'High-performance computing (HPC)'
>>> - 'Improving productivity and sustainability'
>>> - 'Licensing'
>>> - 'Performance at leadership computing facilities (LCFs)'
>>> - 'Performance portability'
>>> - 'Projects and organizations'
>>> - 'Reproducibility'
>>> - 'Requirements'
>>> - 'Software interoperability'
>>> - 'Software publishing and citation'
>>> - 'Strategies for more effective teams'
>>> - 'Testing'
```

## Build Information
- Test Name: BSSW_PR_AutoTest
- Build Num: 22
- Status: FAILED

### Jenkins Parameters
| Parameter Name | Value |
|----------------|-------|
| BSSW_SOURCE_BRANCH | pr-test-fail-02 |
| BSSW_SOURCE_REPO | https://github.com/william76/betterscientificsoftware.github.io |
| BSSW_SOURCE_SHA | a119f6b93d9027a972d60ad6e5ddb898ab3c5a3b |
| BSSW_TARGET_BRANCH | develop |
| BSSW_TARGET_REPO | https://github.com/william76/betterscientificsoftware.github.io |
| BSSW_TARGET_SHA | f2c52140450cd343c6fb8e40c5c6d00e9be283f2 |
| JENKINS_JOB_TYPE | Experimental |
| TEST_REPO_ALIAS | BSSW |

**Comment by william76** [comment]
## Test Comment

<details>
  <summary>Sample Summary Text</summary>
  <p>This is some test text that should be hidden by Markdown</p>
  <table>
  <tr>
  <th>first</th>
  <th>second</th>
  </tr>
   <tr><td>A</td><td>B</td></tr>
   <tr><td>C</td><td>D</td></tr>
  </table>
</details>

**Pull request closed without merging**
